// <auto-generated />
using System;
using System.Reflection;
using IssueTracker.Issues.Domain.Configuration.ValueConverters;
using IssueTracker.Issues.Domain.DataContracts;
using IssueTracker.Issues.Domain.ModelAggregates.IssueAggregate;
using IssueTracker.Issues.Domain.ModelAggregates.IssueAggregate.State;
using IssueTracker.Issues.Infrastructure.Configurations.ValueConverters;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace IssueTracker.Issues.Infrastructure.Data.CompiledModels
{
    internal partial class IssueEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType? baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "IssueTracker.Issues.Domain.ModelAggregates.IssueAggregate.Issue",
                typeof(Issue),
                baseEntityType);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(IssueIdentifier),
                propertyInfo: typeof(Issue).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Issue).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                valueConverter: new IssueIdentifierValueConverter());

            var concurrencyToken = runtimeEntityType.AddProperty(
                "ConcurrencyToken",
                typeof(ulong),
                propertyInfo: typeof(Entity).GetProperty("ConcurrencyToken", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entity).GetField("<ConcurrencyToken>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                concurrencyToken: true,
                valueGenerated: ValueGenerated.OnAdd);
            concurrencyToken.AddAnnotation("Relational:DefaultValue", 0ul);

            var lastModifiedTime = runtimeEntityType.AddProperty(
                "LastModifiedTime",
                typeof(DateTimeOffset),
                propertyInfo: typeof(Entity).GetProperty("LastModifiedTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Entity).GetField("<LastModifiedTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new DateTimeOffsetValueConverter());

            var priority = runtimeEntityType.AddProperty(
                "Priority",
                typeof(Priority),
                propertyInfo: typeof(Issue).GetProperty("Priority", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Issue).GetField("<Priority>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var state = runtimeEntityType.AddProperty(
                "State",
                typeof(IssueState),
                propertyInfo: typeof(Issue).GetProperty("State", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Issue).GetField("<State>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new IssueStateValueConverter());

            var description = runtimeEntityType.AddProperty(
                "_description",
                typeof(string),
                fieldInfo: typeof(Issue).GetField("_description", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field,
                maxLength: 500,
                unicode: true);
            description.AddAnnotation("Relational:ColumnName", "Description");

            var epicId = runtimeEntityType.AddProperty(
                "_epicId",
                typeof(IssueIdentifier?),
                fieldInfo: typeof(Issue).GetField("_epicId", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field,
                nullable: true,
                valueConverter: new NullableIssueIdentifierValueConverter());
            epicId.AddAnnotation("Relational:ColumnName", "EpicId");

            var issueNumber = runtimeEntityType.AddProperty(
                "_issueNumber",
                typeof(int),
                fieldInfo: typeof(Issue).GetField("_issueNumber", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field);
            issueNumber.AddAnnotation("Relational:ColumnName", "IssueNumber");

            var projectId = runtimeEntityType.AddProperty(
                "_projectId",
                typeof(string),
                fieldInfo: typeof(Issue).GetField("_projectId", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field,
                maxLength: 3,
                unicode: false);
            projectId.AddAnnotation("Relational:ColumnName", "ProjectId");

            var startTime = runtimeEntityType.AddProperty(
                "_startTime",
                typeof(DateTimeOffset?),
                fieldInfo: typeof(Issue).GetField("_startTime", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field,
                nullable: true,
                valueConverter: new NullableDateTimeOffsetValueConverter());

            var stopTime = runtimeEntityType.AddProperty(
                "_stopTime",
                typeof(DateTimeOffset?),
                fieldInfo: typeof(Issue).GetField("_stopTime", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field,
                nullable: true,
                valueConverter: new NullableDateTimeOffsetValueConverter());

            var title = runtimeEntityType.AddProperty(
                "_title",
                typeof(string),
                fieldInfo: typeof(Issue).GetField("_title", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field,
                maxLength: 200,
                unicode: true);
            title.AddAnnotation("Relational:ColumnName", "Title");

            var type = runtimeEntityType.AddProperty(
                "_type",
                typeof(IssueType),
                fieldInfo: typeof(Issue).GetField("_type", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                propertyAccessMode: PropertyAccessMode.Field);
            type.AddAnnotation("Relational:ColumnName", "Type");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { priority });

            var index0 = runtimeEntityType.AddIndex(
                new[] { epicId });

            var index1 = runtimeEntityType.AddIndex(
                new[] { issueNumber });

            var index2 = runtimeEntityType.AddIndex(
                new[] { projectId });

            var index3 = runtimeEntityType.AddIndex(
                new[] { title });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("_epicId")! },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id")! })!,
                principalEntityType,
                deleteBehavior: DeleteBehavior.NoAction);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("_projectId")! },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id")! })!,
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            var project = declaringEntityType.AddNavigation("Project",
                runtimeForeignKey,
                onDependent: true,
                typeof(Project),
                propertyInfo: typeof(Issue).GetProperty("Project", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Issue).GetField("<Project>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Issues");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
