// <auto-generated />
using System;
using IssueTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssueTracker.Data.Migrations
{
    [DbContext(typeof(IssuesDbContext))]
    [Migration("20220508005646_AddEpic")]
    partial class AddEpic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("IssueTracker.Core.Model.Issue", b =>
                {
                    b.Property<Guid>("IssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpicIssueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("IssueId");

                    b.HasIndex("EpicIssueId");

                    b.HasIndex("Id");

                    b.HasIndex("IssueNumber");

                    b.HasIndex("Priority");

                    b.HasIndex("Project");

                    b.HasIndex("Title");

                    b.ToTable("Issues", (string)null);

                    b.HasData(
                        new
                        {
                            IssueId = new Guid("06c3e187-0486-4eed-91db-b346a7044879"),
                            ConcurrencyToken = "b2d2aac4-77e6-415a-89b9-711d37f13636",
                            Description = "add projects and use project id as link between issue and project",
                            Id = "APP-1",
                            IssueNumber = 1,
                            LastUpdated = 637766370000000000L,
                            Priority = 2,
                            Project = "APP",
                            Title = "Add Project support",
                            Type = 0
                        },
                        new
                        {
                            IssueId = new Guid("47cc7642-a8ed-4cc7-ba94-3c2ed8fc2165"),
                            ConcurrencyToken = "3d9f247a-82a1-43d4-8928-76a94c245a8d",
                            Description = "",
                            Id = "APP-2",
                            IssueNumber = 2,
                            LastUpdated = 637766376000000000L,
                            Priority = 1,
                            Project = "APP",
                            Title = "The database should story issues with links to projects",
                            Type = 1
                        },
                        new
                        {
                            IssueId = new Guid("cda71c85-f63b-42eb-8f48-f0ad1409e10d"),
                            ConcurrencyToken = "3ced4422-84d5-4d7d-8701-b56d660ac6c1",
                            Description = "As a user I want to be able to retreive all projects",
                            Id = "APP-3",
                            IssueNumber = 3,
                            LastUpdated = 637766379000000000L,
                            Priority = 0,
                            Project = "APP",
                            Title = "The api should be able to retrieve projects",
                            Type = 1
                        },
                        new
                        {
                            IssueId = new Guid("ddbb6026-129b-474e-af0a-4f58a9dd68b4"),
                            ConcurrencyToken = "45217bdc-4936-445d-b6ef-703eab053412",
                            Description = "add the model(s) for project type ensuring it's id matches the expectations of issue",
                            Id = "APP-4",
                            IssueNumber = 4,
                            LastUpdated = 637767216000000000L,
                            Priority = 1,
                            Project = "APP",
                            Title = "add project core models",
                            Type = 2
                        },
                        new
                        {
                            IssueId = new Guid("d180b554-0a2b-4e44-bb57-82075f4f5fbf"),
                            ConcurrencyToken = "254447bd-1ce7-4726-bc95-fe2330cb4556",
                            Description = "add the request handlers to get projects by id and a summary",
                            Id = "APP-5",
                            IssueNumber = 5,
                            LastUpdated = 637768143000000000L,
                            Priority = 0,
                            Project = "APP",
                            Title = "add mediator request/handlers for project query",
                            Type = 2
                        });
                });

            modelBuilder.Entity("IssueTracker.Core.ValueObjects.LinkedIssue", b =>
                {
                    b.Property<Guid>("ParentIssueId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChildIssueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<int>("LinkType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ParentIssueId", "ChildIssueId");

                    b.HasIndex("ChildId");

                    b.HasIndex("ChildIssueId");

                    b.HasIndex("ParentId");

                    b.ToTable("LinkedIssues", (string)null);

                    b.HasData(
                        new
                        {
                            ParentIssueId = new Guid("ddbb6026-129b-474e-af0a-4f58a9dd68b4"),
                            ChildIssueId = new Guid("d180b554-0a2b-4e44-bb57-82075f4f5fbf"),
                            ChildId = "APP-5",
                            ConcurrencyToken = "1c386db3-4549-498c-a55b-49231a9d0ddf",
                            LinkType = 2,
                            ParentId = "APP-4"
                        },
                        new
                        {
                            ParentIssueId = new Guid("47cc7642-a8ed-4cc7-ba94-3c2ed8fc2165"),
                            ChildIssueId = new Guid("cda71c85-f63b-42eb-8f48-f0ad1409e10d"),
                            ChildId = "APP-3",
                            ConcurrencyToken = "4962858d-e5a8-4143-872f-bd19ba370d9c",
                            LinkType = 0,
                            ParentId = "APP-2"
                        });
                });

            modelBuilder.Entity("IssueTracker.Core.Model.Issue", b =>
                {
                    b.HasOne("IssueTracker.Core.Model.Issue", "Epic")
                        .WithMany()
                        .HasForeignKey("EpicIssueId");

                    b.OwnsOne("IssueTracker.Core.ValueObjects.Maintainer", "Assignee", b1 =>
                        {
                            b1.Property<Guid>("IssueId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(200)
                                .IsUnicode(true)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("Unassigned");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                            b1.HasKey("IssueId");

                            b1.ToTable("Issues");

                            b1.WithOwner()
                                .HasForeignKey("IssueId");
                        });

                    b.OwnsOne("IssueTracker.Core.ValueObjects.TriageUser", "Reporter", b1 =>
                        {
                            b1.Property<Guid>("IssueId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(200)
                                .IsUnicode(true)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("Unassigned");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                            b1.HasKey("IssueId");

                            b1.ToTable("Issues");

                            b1.WithOwner()
                                .HasForeignKey("IssueId");
                        });

                    b.Navigation("Assignee")
                        .IsRequired();

                    b.Navigation("Epic");

                    b.Navigation("Reporter")
                        .IsRequired();
                });

            modelBuilder.Entity("IssueTracker.Core.ValueObjects.LinkedIssue", b =>
                {
                    b.HasOne("IssueTracker.Core.Model.Issue", "ChildIssue")
                        .WithMany("ChildIssueEntities")
                        .HasForeignKey("ChildIssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IssueTracker.Core.Model.Issue", "ParentIssue")
                        .WithMany("ParentIssueEntities")
                        .HasForeignKey("ParentIssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildIssue");

                    b.Navigation("ParentIssue");
                });

            modelBuilder.Entity("IssueTracker.Core.Model.Issue", b =>
                {
                    b.Navigation("ChildIssueEntities");

                    b.Navigation("ParentIssueEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
