// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace IssueTracker.Issues.Infrastructure.CompiledModels
{
    [DbContext(typeof(IssuesDbContext))]
    public partial class IssuesDbContextModel : RuntimeModel
    {
        static IssuesDbContextModel()
        {
            var model = new IssuesDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static IssuesDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
