// <auto-generated />
using System;
using IssueTracker.App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssueTracker.App.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220219012145_IssueConcurrencyToen")]
    partial class IssueConcurrencyToen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("IssueTracker.App.Model.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Priority");

                    b.ToTable("Issues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8cd2eb4-6559-437f-a1f9-3adb7b886382"),
                            ConcurrencyToken = "b7a843f5-6834-4d13-95b7-07fadc6ced87",
                            Description = "First issue",
                            LastUpdated = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "First",
                            Priority = 1
                        },
                        new
                        {
                            Id = new Guid("7b4079ce-bead-4fa6-9c2e-6fb4b853615a"),
                            ConcurrencyToken = "eb372a55-1209-449b-b499-d7c2894bd8cc",
                            Description = "Second issue",
                            LastUpdated = new DateTime(2022, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Second",
                            Priority = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
