// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace IssueTracker.Issues.Infrastructure.CompiledModels
{
    public partial class IssuesDbContextModel
    {
        partial void Initialize()
        {
            var issue = IssueEntityType.Create(this);
            var issueLink = IssueLinkEntityType.Create(this);
            var maintainer = MaintainerEntityType.Create(this);
            var triageUser = TriageUserEntityType.Create(this);

            IssueEntityType.CreateForeignKey1(issue, issue);
            IssueLinkEntityType.CreateForeignKey1(issueLink, issue);
            IssueLinkEntityType.CreateForeignKey2(issueLink, issue);
            MaintainerEntityType.CreateForeignKey1(maintainer, issue);
            TriageUserEntityType.CreateForeignKey1(triageUser, issue);

            IssueEntityType.CreateAnnotations(issue);
            IssueLinkEntityType.CreateAnnotations(issueLink);
            MaintainerEntityType.CreateAnnotations(maintainer);
            TriageUserEntityType.CreateAnnotations(triageUser);

            AddAnnotation("ProductVersion", "6.0.5");
        }
    }
}
