name: CI dotnet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-net6:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.412
    - name: Restore dependencies
      working-directory: v1/net6
      run: dotnet restore
    - name: Build
      working-directory: v1/net6
      run: dotnet build --no-restore
    - name: Test
      working-directory: v1/net6
      run: dotnet test --no-build --verbosity normal
  
  build-net7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.306
    - name: Restore dependencies
      working-directory: v1/net7
      run: dotnet restore
    - name: Build
      working-directory: v1/net7
      run: dotnet build --no-restore
    - name: Test
      working-directory: v1/net7
      run: dotnet test --no-build --verbosity normal
