// <auto-generated />
using System;
using IssueTracker.Issues.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IssueTracker.Issues.Infrastructure.Migrations
{
    [DbContext(typeof(IssuesDbContext))]
    [Migration("20220510235324_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("IssueTracker.Issues.Domain.ModelAggregates.IssueAggregate.Issue", b =>
                {
                    b.Property<Guid>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EpidId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastModifiedTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("_epicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("_epidId")
                        .HasColumnType("TEXT");

                    b.Property<int>("_issueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_project")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("_id");

                    b.HasIndex("Priority");

                    b.HasIndex("Title");

                    b.HasIndex("_epidId");

                    b.HasIndex("_id");

                    b.HasIndex("_issueNumber");

                    b.HasIndex("_project");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("IssueTracker.Issues.Domain.ModelAggregates.IssueAggregate.Issue", b =>
                {
                    b.HasOne("IssueTracker.Issues.Domain.ModelAggregates.IssueAggregate.Issue", null)
                        .WithMany()
                        .HasForeignKey("_epidId");

                    b.OwnsOne("IssueTracker.Issues.Domain.ModelAggregates.IssueAggregate.Maintainer", "Assignee", b1 =>
                        {
                            b1.Property<Guid>("Issue_id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(200)
                                .IsUnicode(true)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("Unassigned");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                            b1.HasKey("Issue_id");

                            b1.ToTable("Issues");

                            b1.WithOwner()
                                .HasForeignKey("Issue_id");
                        });

                    b.OwnsOne("IssueTracker.Issues.Domain.ModelAggregates.IssueAggregate.TriageUser", "Reporter", b1 =>
                        {
                            b1.Property<Guid>("Issue_id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(200)
                                .IsUnicode(true)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("Unassigned");

                            b1.Property<Guid>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"));

                            b1.HasKey("Issue_id");

                            b1.ToTable("Issues");

                            b1.WithOwner()
                                .HasForeignKey("Issue_id");
                        });

                    b.Navigation("Assignee")
                        .IsRequired();

                    b.Navigation("Reporter")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
